### ISSUE TITLE
Add support for JS logging

### ISSUE THREAD

**Issue by YarnSphere** [wswartzendruber/la4k#1]
Hey, I'm interested in this library's approach to logging as I'm currently using `kotlin-logging` and I do find your approach more sensible.

However, since I'm mostly involved in Kotlin MPP with JS, I cannot make the move and try this out until JS support is provided.
I hope you don't mind me creating this issue mainly for me to track progress on logging for JS, even if I end up just receiving a "merged/closed" notification at some point! :)

Now, in terms of implementation, I read a comment of yours on Reddit saying that you're planning on providing logging for JS by integrating with `winston` in a `la4k-winston`. My question for you is: how do you plan on tackling browser logging?

This is an open issue on `winston`'s issue tracker: https://github.com/winstonjs/winston/issues/287 and I'm not sure if there is already a "good" solution for it, even though some solutions seem to have appeared.

I don't exactly have any metrics on this, but I'd guess that **most** `kotlin-js` and `kotlin-multiplatform` projects target browser JS and don't much care about Node, so my take on this is that browser logging is likely more important than logging on Node, or at least for me it is.

At least in my case, as a library developer, I'm interested in allowing library users to "turn on" browser logging in development mode when using my library, so that they can see library logs as "things happen" in the browser.

What are your thoughts on this? What's your take on JS logging and browser logging in general?

**Comment by YarnSphere** [comment]
This could possibly be used until `winston` has an "official" solution: https://www.npmjs.com/package/winston-transport-browserconsole (also suggested in the issue linked above).

Would it be provided by `la4k-winston` by default?

**Comment by wswartzendruber** [comment]
I am so sorry. It is December 20th, and I have only just now noticed your issue. I will respond sometime tomorrow in more detail.

**Comment by wswartzendruber** [comment]
I've reread what you posted and read over the Winston issue you provided. From what I can see, you want users of your library to be able to have logging regardless of where your library is being run. To this end, I'm not sure trying to cram Winston in the browser is the best way to go. Ultimately, where do you want browser logs to end up?

I released LA4K 0.5.0 yesterday. `la4k-winston` is present for NodeJS targets, but all targets (including the browser), also have a `la4k-console` bridge available. This just prints logging events via Kotlin's `println()` function. See [here](https://github.com/wswartzendruber/la4k/tree/3cd230fd98c0363984c68391f735e56bfb197783/la4k-console).

I haven't messed with LA4K in the browser yet, you will need (I think) to include the JS for la4k-api and la4k-console. Then activate the bridge (documented in the link above), then include the JS for your library.

**Comment by YarnSphere** [comment]
Yeah, I explored the repo a bit after your comment. `la4k-console` is all I need, I believe. I just want users of the library to be able to see logs in the browser console during development.

Thanks! Hopefully I'll give this library a try at some point, for now I'll close this issue as the support for JS seems to be here already! :)

**Comment by wswartzendruber** [comment]
Very well. Please reopen this issue if you have difficulties.

**Comment by wswartzendruber** [comment]
@nunocastromartins - I wanted to check in with you and see how things are going with regard to this library.

**Comment by YarnSphere** [comment]
Hey, thanks for checking in but unfortunately I've got nothing to report. The development of the project in which I was considering using this library is currently halted until I finish a different project. This is currently on my backlog but I won't get to it until possibly quite a bit in the future.
